# nixpacks.toml

[build]
# Указываем, что мы используем Nix для сборки
providers = ["nix"]

[nix]
# Список пакетов, которые нужно установить в среде сборки
packages = [
  "nodejs_20", # Убедитесь, что версия Node.js соответствует вашей
  "npm",
  "chromium"   # Это гарантирует, что сам пакет Chromium будет установлен
]

# ---> Ключевая часть для исправления ошибки <---
# Здесь мы настраиваем переменные окружения.
# Nixpacks позволяет ссылаться на установленные пакеты.
[nix.env]
# Устанавливаем переменную окружения CHROMIUM_PATH.
# Nixpacks преобразует "$pkgs.chromium/bin/chromium" в реальный путь
# к исполняемому файлу chromium в Nix-хранилище.
# Ваш код, вероятно, ищет эту переменную.
CHROMIUM_PATH = "$pkgs.chromium/bin/chromium"