# nixpacks.toml

# Указываем, что для сборки будет использоваться Nix-менеджер пакетов.
[build]
providers = ["nix"]

# Конфигурация Nix
[nix]
# Мы хотим использовать Node.js версии 20.
# nodejsSetup гарантирует, что PATH и окружение будут настроены корректно.
nodejsSetup = { version = "20" }

# Список других пакетов, которые нужны вашему сервису.
packages = [
  "npm",          # npm обычно идет вместе с Node.js, но явно указать не повредит.
  "chromium",     # Сам браузер Chromium, необходимый для конвертации.
  # Добавьте любые другие системные библиотеки, если они требуются вашему сервису
  # (например, libgbm, freetype, pango и т.д., если ваш сервис их использует в сборке)
  # "libpng", "freetype", "pango", "libgbm", "libcups"
]

# ==========================================================
#              Переменные окружения
# ==========================================================
# Это критически важно. Библиотеки для работы с браузерами
# (Puppeteer, Playwright) ищут эти переменные.
[nix.env]
# Указываем путь к исполняемому файлу Chromium. Nixpacks преобразует
# '$pkgs.chromium' в реальный путь к исполняемому файлу в Nix-store.
CHROMIUM_PATH = "$pkgs.chromium/bin/chromium"
PUPPETEER_EXECUTABLE_PATH = "$pkgs.chromium/bin/chromium" # Дополнительно, если код использует эту переменную

# ==========================================================
#                КОМАНДЫ СТАРТА
# ==========================================================
# Важно явно указать команды. Это гарантирует, что они будут
# запущены в среде, настроенной Nix (с Node.js v20).

# Команда для установки зависимостей. 'npm ci' предпочтительнее для CI/CD
# чем 'npm install', так как он быстрее и надежнее.
installCommand = "npm ci"

# Команда для запуска вашего приложения.
# Предполагается, что у вас есть скрипт "start" в package.json,
# который, например, запускает 'node index.js'.
#
# *** ДОПОЛНИТЕЛЬНОЕ ИСПРАВЛЕНИЕ ***
# Чтобы гарантировать, что `npm start` запускается с правильным окружением,
# мы явно передадим CHROMIUM_PATH прямо в команду. Это может помочь
# обойти проблемы наследования переменных окружения.
startCommand = "CHROMIUM_PATH=\"$pkgs.chromium/bin/chromium\" npm start"