# nixpacks.toml

[build]
# Указываем, что для сборки будет использоваться Nix
providers = ["nix"]

[nix]
# Список пакетов, которые Nix должен установить в среде:
packages = [
  "nodejs_20", # Убедитесь, что версия Node.js актуальна для вашего проекта
  "npm",
  "chromium"   # Это установит сам пакет Chromium
]

# =======================================================
#                 ВАЖНАЯ СЕКЦИЯ:
#      Здесь мы настраиваем переменные окружения.
# =======================================================
[nix.env]
# Nixpacks автоматически разрешает $pkgs.chromium
# в реальный путь к исполняемому файлу chromium.
# Ваш код, который выполняет конвертацию в PDF,
# скорее всего, ожидает найти браузер по этой переменной.
CHROMIUM_PATH = "$pkgs.chromium/bin/chromium"

# Опционально: Если ваш код использует другую переменную для пути к браузеру
# (например, PUPPETEER_EXECUTABLE_PATH, если вы используете Puppeteer
# и он настроен иначе), добавьте ее сюда. Но CHROMIUM_PATH — наиболее
# частый вариант.
# PUPPETEER_EXECUTABLE_PATH = "$pkgs.chromium/bin/chromium"
# =======================================================